### ISSUE TITLE
only one of the two motors turns 

### ISSUE THREAD

**Issue by Nij-alter** [ironsheep/P2-BLDC-Motor-Control#4]
hello, 

I'm running demo_dual_motor.spin2, and I have adjusted the contents of isp_bldc_motor_userconfig.spin2 to the following:

    MOTOR_TYPE = MOTR_6_5_INCH

    LEFT_MOTOR_BASE = PINS_P0_P15
    RIGHT_MOTOR_BASE = PINS_P16_P31

    DRIVE_VOLTAGE = PWR_12V

    WHEEL_DIA_IN_INCH = 6.5 

when I upload the demo to the p2 edge, only the motor on the side of the 16-31 pins moves, the one on the side of 0-15 doesn't.
I checked the 0-15 pins with a multimeter and they have 0V 

please help

**Comment by ironsheep** [comment]
@Nij-alter what version of the code are you using and how did you download it?  Have you tried the latest .zip files?

Also, do you the motor power going to both boards?  (Maybe a silly question but I'm trying to be complete ;-)

**Comment by Nij-alter** [comment]
I downloaded the entire folder from GitHub 2 days ago, and yes I have indeed connected power to both drivers with fuses on each of the +Ve lines. What I'm trying to understand is whether this is a software or a hardware problem

**Comment by Nij-alter** [comment]
oh, I am not using the eval board, I'm using the edge module with the mini breakout board. With that said I've tried to flip the drivers around and the results were the same, 16-31 are functional and 0-15 are not. I also measured the signal output of the pins and there is no PWM coming the latter.

**Comment by ironsheep** [comment]
I'm running similar platform to you.  [My System](https://github.com/ironsheep/P2-BLDC-Motor-Control/blob/main/AUTHORS-Platform.md). I just ran the attached code (latest from the repo) and it's turning both motors.   Please see if it does the same for you.

[demo_dual_motor - Archive  [Date 2022.07.14  Time 14.42].zip](https://github.com/ironsheep/P2-BLDC-Motor-Control/files/9115235/demo_dual_motor.-.Archive.Date.2022.07.14.Time.14.42.zip)

**Comment by Nij-alter** [comment]
i ran the code from the folder above and the result is still the same.

**Comment by ironsheep** [comment]
OK, then we are more likely chasing a hardware issue.

Q1: The consistent thing is that any "driver-board, motor" pair on p0-p15 doesn't work, am I right?

Q2: Do you have another mini-breakout board?  Or do you have a JonnyMac board?

**Comment by Nij-alter** [comment]
Q1: correct I have 2 sets of motor driver pairs and none of them are functioning on those pins 

Q2/Q3: I do not have any other parts

is there a way to send like a dummy code to the 0-15 pins and check if they indeed can emit signals or not? something like analogwrite for Arduino ?

**Comment by ironsheep** [comment]
Oh, also, since you moved the boards to the other connector pair that also tested both motor-boards and both motors and they work, right?

Re: dummy code, yes. But it wouldn't accomplish anything as the pins on the motor boards are fixed to their locations.

We can go further in isolating the problem to specific P0-p15 pins by creating special software and then you looking for the signal we are writing to the pins.  Do you have a logic analyzer or scope? Or what would you use?

We can also come up with some sort of signal or voltage to place on each pin to see if we can read those values at P0-P15.

In the end, we really need to know which part needs a replacement: (A) the P2 Edge or (B) the mini breakout board, right?
Am I missing anything?

**Comment by Nij-alter** [comment]
yes exactly 
I have an Arduino that I can use to read PWM and a multimeter. 
would that help?

**Comment by ironsheep** [comment]
**NOTE: please remove the motor board from P0-P15 before running these tests...**

**WRITE TEST**

Ok, here's some sample code to simply toggle the pins 0-15.  Set the low time and high time so you can see it change with the meter.  Go to each pin and see which if any are not behaving correctly. (the code has repeat forever 3 sec LOW then 5 sec HIGH for all P0-P15 at the same time.)

[test_pins_toggle - Archive  [Date 2022.07.14  Time 17.11].zip](https://github.com/ironsheep/P2-BLDC-Motor-Control/files/9116515/test_pins_toggle.-.Archive.Date.2022.07.14.Time.17.11.zip)

After you check all 16 pins you will know if you have an output problem.

**READ TEST**

The next thing you'll want to do is read from all 15 pins and display the output. Run the next archive with debugging on then simply ground each pin one by one and you will know which pins are not reading correctly after you've tested them all.

[test_pins_read - Archive  [Date 2022.07.14  Time 17.24].zip](https://github.com/ironsheep/P2-BLDC-Motor-Control/files/9116562/test_pins_read.-.Archive.Date.2022.07.14.Time.17.24.zip)

After you check all 16 pins this time, you will know if you have any input problems.

**ISOLATE P2 EDGE vs. Breakout board**

I look forward to hearing what you find.  Of course, the next step is to focus on seeing if the issue is with the P2 EDGE or the breakout board.  You might be able to check this by probing the failing pins at the edge connect as it goes into the socket.  Learning which pins are failing first will make this later probing easier in that you only need to check the pins that are failing.

This help?

**Comment by Nij-alter** [comment]
yess i did this write test 

when the pins are supposed to be high, all the pins show 3.3V except 8-10 which show 0V

**Comment by ironsheep** [comment]
Good to see a result, not happy at it of course.

Let's see what you have for the read side? 

Also, do you see anything that could be grounding those three pins?

Have you tried removing and re-seating the P2 Edge module? And was it seated well to start with?

**Comment by ironsheep** [comment]
@Nij-alter any more news/findings?

**Comment by Nij-alter** [comment]
no I gave up to be honest, the project is timely and i need to figure out how to drive the motor some other way ...

**Comment by ironsheep** [comment]
Sorry to hear...  is there anything near the board underneath that could be shorting?

Anyway, let me know if you have any further questions...

**Comment by Nij-alter** [comment]
nope it was on a wooden surface. thank you for all the help. cheers
